In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
customers = pd.read_csv("../data/blinkit_customers.csv")

orders = pd.read_csv("../data/blinkit_orders.csv")

order_items = pd.read_csv("../data/blinkit_order_items.csv")

products = pd.read_csv("../data/blinkit_products.csv")

inventory = pd.read_csv("../data/blinkit_inventory.csv")

inventory_new = pd.read_csv("../data/blinkit_inventoryNew.csv")

delivery = pd.read_csv("../data/blinkit_delivery_performance.csv")

feedback = pd.read_csv("../data/blinkit_customer_feedback.csv")

marketing = pd.read_csv("../data/blinkit_marketing_performance.csv")

In [3]:
def audit_dataset(df, name):
    
    print("=" * 80)
    print(name.upper())
    print("=" * 80)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nSample:")
    display(df.head())

In [4]:
audit_dataset(customers, "Customers")

audit_dataset(orders, "Orders")

audit_dataset(order_items, "Order Items")

audit_dataset(products, "Products")

audit_dataset(inventory, "Inventory")

audit_dataset(inventory_new, "Inventory New")

audit_dataset(delivery, "Delivery")

audit_dataset(feedback, "Feedback")

audit_dataset(marketing, "Marketing")

================================================================================
CUSTOMERS
================================================================================

Shape:
(2500, 11)

Columns:
['customer_id', 'customer_name', 'email', 'phone', 'address', 'area', 'pincode', 'registration_date', 'customer_segment', 'total_orders', 'avg_order_value']

Data Types:
customer_id            int64
customer_name         object
email                 object
phone                  int64
address               object
area                  object
pincode                int64
registration_date     object
customer_segment      object
total_orders           int64
avg_order_value      float64
dtype: object

Missing Values:
customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64

Duplicate Rows:
0

Sample:

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09
4,57102800,Januja Verma,atideshpande@example.org,917293526596,"06\nOm, Ambarnath 477463",Ichalkaranji,730539,2024-03-22,Inactive,14,578.14

================================================================================
ORDERS
================================================================================

Shape:
(5000, 10)

Columns:
['order_id', 'customer_id', 'order_date', 'promised_delivery_time', 'actual_delivery_time', 'delivery_status', 'order_total', 'payment_method', 'delivery_partner_id', 'store_id']

Data Types:
order_id                    int64
customer_id                 int64
order_date                 object
promised_delivery_time     object
actual_delivery_time       object
delivery_status            object
order_total               float64
payment_method             object
delivery_partner_id         int64
store_id                    int64
dtype: object

Missing Values:
order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64

Duplicate Rows:
0

Sample:

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

================================================================================
ORDER ITEMS
================================================================================

Shape:
(5000, 4)

Columns:
['order_id', 'product_id', 'quantity', 'unit_price']

Data Types:
order_id        int64
product_id      int64
quantity        int64
unit_price    float64
dtype: object

Missing Values:
order_id      0
product_id    0
quantity      0
unit_price    0
dtype: int64

Duplicate Rows:
0

Sample:

     order_id  product_id  quantity  unit_price
0  1961864118      642612         3      517.03
1  1549769649      378676         1      881.42
2  9185164487      741341         2      923.84
3  9644738826      561860         1      874.78
4  5427684290      602241         2      976.55

================================================================================
PRODUCTS
================================================================================

Shape:
(268, 10)

Columns:
['product_id', 'product_name', 'category', 'brand', 'price', 'mrp', 'margin_percentage', 'shelf_life_days', 'min_stock_level', 'max_stock_level']

Data Types:
product_id             int64
product_name          object
category              object
brand                 object
price                float64
mrp                  float64
margin_percentage    float64
shelf_life_days        int64
min_stock_level        int64
max_stock_level        int64
dtype: object

Missing Values:
product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64

Duplicate Rows:
0

Sample:

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55

================================================================================
INVENTORY
================================================================================

Shape:
(75172, 4)

Columns:
['product_id', 'date', 'stock_received', 'damaged_stock']

Data Types:
product_id         int64
date              object
stock_received     int64
damaged_stock      int64
dtype: object

Missing Values:
product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64

Duplicate Rows:
0

Sample:

   product_id        date  stock_received  damaged_stock
0      153019  17-03-2023               4              2
1      848226  17-03-2023               4              2
2      965755  17-03-2023               1              0
3       39154  17-03-2023               4              0
4       34186  17-03-2023               3              2

================================================================================
INVENTORY NEW
================================================================================

Shape:
(18105, 4)

Columns:
['product_id', 'date', 'stock_received', 'damaged_stock']

Data Types:
product_id         int64
date              object
stock_received     int64
damaged_stock      int64
dtype: object

Missing Values:
product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64

Duplicate Rows:
7359

Sample:

   product_id    date  stock_received  damaged_stock
0      153019  Mar-23               4              1
1      848226  Mar-23               4              1
2      965755  Mar-23               1              0
3       39154  Mar-23               4              0
4       34186  Mar-23               3              1

================================================================================
DELIVERY
================================================================================

Shape:
(5000, 8)

Columns:
['order_id', 'delivery_partner_id', 'promised_time', 'actual_time', 'delivery_time_minutes', 'distance_km', 'delivery_status', 'reasons_if_delayed']

Data Types:
order_id                   int64
delivery_partner_id        int64
promised_time             object
actual_time               object
delivery_time_minutes    float64
distance_km              float64
delivery_status           object
reasons_if_delayed        object
dtype: object

Missing Values:
order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

Duplicate Rows:
0

Sample:

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,NaN
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,NaN
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic

================================================================================
FEEDBACK
================================================================================

Shape:
(5000, 8)

Columns:
['feedback_id', 'order_id', 'customer_id', 'rating', 'feedback_text', 'feedback_category', 'sentiment', 'feedback_date']

Data Types:
feedback_id           int64
order_id              int64
customer_id           int64
rating                int64
feedback_text        object
feedback_category    object
sentiment            object
feedback_date        object
dtype: object

Missing Values:
feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

Duplicate Rows:
0

Sample:

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20

================================================================================
MARKETING
================================================================================

Shape:
(5400, 11)

Columns:
['campaign_id', 'campaign_name', 'date', 'target_audience', 'channel', 'impressions', 'clicks', 'conversions', 'spend', 'revenue_generated', 'roas']

Data Types:
campaign_id            int64
campaign_name         object
date                  object
target_audience       object
channel               object
impressions            int64
clicks                 int64
conversions            int64
spend                float64
revenue_generated    float64
roas                 float64
dtype: object

Missing Values:
campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64

Duplicate Rows:
0

Sample:

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95
3,241523,Flash Sale,2024-11-05,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22

In [5]:
print("""
CUSTOMERS

Purpose:
Customer demographics and behavioral analysis

Dashboard Pages:
- Executive Overview
- Customer Intelligence
""")

CUSTOMERS

Purpose:
Customer demographics and behavioral analysis

Dashboard Pages:
- Executive Overview
- Customer Intelligence

In [7]:
datasets = {
    "Customers": customers,
    "Orders": orders,
    "Order Items": order_items,
    "Products": products,
    "Inventory": inventory,
    "Inventory New": inventory_new,
    "Delivery": delivery,
    "Feedback": feedback,
    "Marketing": marketing
}

In [8]:
for name, df in datasets.items():
    
    print(f"\n{name}")

    print("Missing %")

    print((df.isnull().sum() / len(df)) * 100)

    print("-" * 50)

Customers
Missing %
customer_id          0.0
customer_name        0.0
email                0.0
phone                0.0
address              0.0
area                 0.0
pincode              0.0
registration_date    0.0
customer_segment     0.0
total_orders         0.0
avg_order_value      0.0
dtype: float64
--------------------------------------------------

Orders
Missing %
order_id                  0.0
customer_id               0.0
order_date                0.0
promised_delivery_time    0.0
actual_delivery_time      0.0
delivery_status           0.0
order_total               0.0
payment_method            0.0
delivery_partner_id       0.0
store_id                  0.0
dtype: float64
--------------------------------------------------

Order Items
Missing %
order_id      0.0
product_id    0.0
quantity      0.0
unit_price    0.0
dtype: float64
--------------------------------------------------

Products
Missing %
product_id           0.0
product_name         0.0
category             0.0
brand                0.0
price                0.0
mrp                  0.0
margin_percentage    0.0
shelf_life_days      0.0
min_stock_level      0.0
max_stock_level      0.0
dtype: float64
--------------------------------------------------

Inventory
Missing %
product_id        0.0
date              0.0
stock_received    0.0
damaged_stock     0.0
dtype: float64
--------------------------------------------------

Inventory New
Missing %
product_id        0.0
date              0.0
stock_received    0.0
damaged_stock     0.0
dtype: float64
--------------------------------------------------

Delivery
Missing %
order_id                  0.00
delivery_partner_id       0.00
promised_time             0.00
actual_time               0.00
delivery_time_minutes     0.00
distance_km               0.00
delivery_status           0.00
reasons_if_delayed       38.04
dtype: float64
--------------------------------------------------

Feedback
Missing %
feedback_id          0.0
order_id             0.0
customer_id          0.0
rating               0.0
feedback_text        0.0
feedback_category    0.0
sentiment            0.0
feedback_date        0.0
dtype: float64
--------------------------------------------------

Marketing
Missing %
campaign_id          0.0
campaign_name        0.0
date                 0.0
target_audience      0.0
channel              0.0
impressions          0.0
clicks               0.0
conversions          0.0
spend                0.0
revenue_generated    0.0
roas                 0.0
dtype: float64
--------------------------------------------------

In [9]:
output_path = "../exports/cleaned_data/"

In [10]:
customers.to_csv(
    output_path + "customers_clean.csv",
    index=False
)

In [11]:
for name, df in datasets.items():
    
    print("\n" + "="*80)
    print(name)
    print("="*80)

    print(f"Shape: {df.shape}")

    print("\nColumns:")
    for col in df.columns:
        print(col)

================================================================================
Customers
================================================================================
Shape: (2500, 11)

Columns:
customer_id
customer_name
email
phone
address
area
pincode
registration_date
customer_segment
total_orders
avg_order_value

================================================================================
Orders
================================================================================
Shape: (5000, 10)

Columns:
order_id
customer_id
order_date
promised_delivery_time
actual_delivery_time
delivery_status
order_total
payment_method
delivery_partner_id
store_id

================================================================================
Order Items
================================================================================
Shape: (5000, 4)

Columns:
order_id
product_id
quantity
unit_price

================================================================================
Products
================================================================================
Shape: (268, 10)

Columns:
product_id
product_name
category
brand
price
mrp
margin_percentage
shelf_life_days
min_stock_level
max_stock_level

================================================================================
Inventory
================================================================================
Shape: (75172, 4)

Columns:
product_id
date
stock_received
damaged_stock

================================================================================
Inventory New
================================================================================
Shape: (18105, 4)

Columns:
product_id
date
stock_received
damaged_stock

================================================================================
Delivery
================================================================================
Shape: (5000, 8)

Columns:
order_id
delivery_partner_id
promised_time
actual_time
delivery_time_minutes
distance_km
delivery_status
reasons_if_delayed

================================================================================
Feedback
================================================================================
Shape: (5000, 8)

Columns:
feedback_id
order_id
customer_id
rating
feedback_text
feedback_category
sentiment
feedback_date

================================================================================
Marketing
================================================================================
Shape: (5400, 11)

Columns:
campaign_id
campaign_name
date
target_audience
channel
impressions
clicks
conversions
spend
revenue_generated
roas

In [12]:
for name, df in datasets.items():
    
    print(f"\n{name}")
    print("-"*50)

    print("Duplicates:", df.duplicated().sum())

Customers
--------------------------------------------------
Duplicates: 0

Orders
--------------------------------------------------
Duplicates: 0

Order Items
--------------------------------------------------
Duplicates: 0

Products
--------------------------------------------------
Duplicates: 0

Inventory
--------------------------------------------------
Duplicates: 0

Inventory New
--------------------------------------------------
Duplicates: 7359

Delivery
--------------------------------------------------
Duplicates: 0

Feedback
--------------------------------------------------
Duplicates: 0

Marketing
--------------------------------------------------
Duplicates: 0

In [13]:
for name, df in datasets.items():
    
    print("\n" + "="*80)
    print(name)
    print("="*80)

    print("Shape:", df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

================================================================================
Customers
================================================================================
Shape: (2500, 11)

Columns:
['customer_id', 'customer_name', 'email', 'phone', 'address', 'area', 'pincode', 'registration_date', 'customer_segment', 'total_orders', 'avg_order_value']

================================================================================
Orders
================================================================================
Shape: (5000, 10)

Columns:
['order_id', 'customer_id', 'order_date', 'promised_delivery_time', 'actual_delivery_time', 'delivery_status', 'order_total', 'payment_method', 'delivery_partner_id', 'store_id']

================================================================================
Order Items
================================================================================
Shape: (5000, 4)

Columns:
['order_id', 'product_id', 'quantity', 'unit_price']

================================================================================
Products
================================================================================
Shape: (268, 10)

Columns:
['product_id', 'product_name', 'category', 'brand', 'price', 'mrp', 'margin_percentage', 'shelf_life_days', 'min_stock_level', 'max_stock_level']

================================================================================
Inventory
================================================================================
Shape: (75172, 4)

Columns:
['product_id', 'date', 'stock_received', 'damaged_stock']

================================================================================
Inventory New
================================================================================
Shape: (18105, 4)

Columns:
['product_id', 'date', 'stock_received', 'damaged_stock']

================================================================================
Delivery
================================================================================
Shape: (5000, 8)

Columns:
['order_id', 'delivery_partner_id', 'promised_time', 'actual_time', 'delivery_time_minutes', 'distance_km', 'delivery_status', 'reasons_if_delayed']

================================================================================
Feedback
================================================================================
Shape: (5000, 8)

Columns:
['feedback_id', 'order_id', 'customer_id', 'rating', 'feedback_text', 'feedback_category', 'sentiment', 'feedback_date']

================================================================================
Marketing
================================================================================
Shape: (5400, 11)

Columns:
['campaign_id', 'campaign_name', 'date', 'target_audience', 'channel', 'impressions', 'clicks', 'conversions', 'spend', 'revenue_generated', 'roas']

In [14]:
summary = []

for name, df in datasets.items():

    summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Duplicate Rows": df.duplicated().sum()
    })

summary_df = pd.DataFrame(summary)

summary_df

         Dataset   Rows  Columns  Duplicate Rows
0      Customers   2500       11               0
1         Orders   5000       10               0
2    Order Items   5000        4               0
3       Products    268       10               0
4      Inventory  75172        4               0
5  Inventory New  18105        4            7359
6       Delivery   5000        8               0
7       Feedback   5000        8               0
8      Marketing   5400       11               0

In [15]:
for name, df in datasets.items():
    
    schema = pd.DataFrame({
        "Column": df.columns,
        "DataType": df.dtypes.values
    })

    schema.to_csv(
        f"../exports/{name.lower().replace(' ','_')}_schema.csv",
        index=False
    )

In [16]:
inventory_new.duplicated().sum()

7359

In [17]:
inventory_new[inventory_new.duplicated()].head(20)

     product_id    date  stock_received  damaged_stock
129      661577  Mar-23               3              0
160      329351  Mar-23               3              0
161      883013  Mar-23               3              0
175      272170  Mar-23               3              0
179      807452  Mar-23               2              0
193      647462  Mar-23               3              0
200        6405  Mar-23               3              0
204      707935  Mar-23               3              0
254      993331  Mar-23               1              0
256      677542  Mar-23               1              0
269      723678  Mar-23               1              0
276       11422  Mar-23               4              0
277      818990  Mar-23               1              0
283      891833  Mar-23               1              0
295      876139  Mar-23               1              0
297      120532  Mar-23               1              0
305      697683  Mar-23               1              0
321      516376  Mar-23               1              0
328      578097  Mar-23               1              0
329      654623  Mar-23               1              0

In [ ]:
inventory_new.shape

(18105, 4)

In [19]:
inventory_new.drop_duplicates().shape

(10746, 4)

In [20]:
inventory_new = inventory_new.drop_duplicates()

In [21]:
inventory_new.to_csv(
    "../exports/cleaned_data/inventory_new_clean.csv",
    index=False
)

In [22]:
for name, df in datasets.items():
    
    print("\n" + "="*60)
    print(name)
    print("="*60)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Missing Values:", df.isnull().sum().sum())
    print("Duplicates:", df.duplicated().sum())

============================================================
Customers
============================================================
Rows: 2500
Columns: 11
Missing Values: 0
Duplicates: 0

============================================================
Orders
============================================================
Rows: 5000
Columns: 10
Missing Values: 0
Duplicates: 0

============================================================
Order Items
============================================================
Rows: 5000
Columns: 4
Missing Values: 0
Duplicates: 0

============================================================
Products
============================================================
Rows: 268
Columns: 10
Missing Values: 0
Duplicates: 0

============================================================
Inventory
============================================================
Rows: 75172
Columns: 4
Missing Values: 0
Duplicates: 0

============================================================
Inventory New
============================================================
Rows: 18105
Columns: 4
Missing Values: 0
Duplicates: 7359

============================================================
Delivery
============================================================
Rows: 5000
Columns: 8
Missing Values: 1902
Duplicates: 0

============================================================
Feedback
============================================================
Rows: 5000
Columns: 8
Missing Values: 0
Duplicates: 0

============================================================
Marketing
============================================================
Rows: 5400
Columns: 11
Missing Values: 0
Duplicates: 0

In [1]:
output_path = "../exports/cleaned_data/"

In [4]:
import pandas as pd
customers = pd.read_csv("../data/customers.csv")
orders = pd.read_csv("../data/orders.csv")
order_items = pd.read_csv("../data/order_items.csv")
products = pd.read_csv("../data/products.csv")
inventory = pd.read_csv("../data/inventory.csv")
inventory_new = pd.read_csv("../data/inventory_new.csv")
delivery = pd.read_csv("../data/delivery_performance.csv")
feedback = pd.read_csv("../data/customer_feedback.csv")
marketing = pd.read_csv("../data/marketing_performance.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/customers.csv'

In [5]:
import os

os.getcwd()

'd:\\Blinkit Retail Intelligence & Supply Chain Analytics Dashboard\\notebooks'

In [6]:
os.listdir("../")

['assets',
 'dashboard',
 'data',
 'exports',
 'notebooks',
 'README.md',
 'screenshots']

In [7]:
os.listdir()

['01_data_cleaning.ipynb',
 '02_eda.ipynb',
 '03_feature_engineering.ipynb',
 '04_customer_segmentation.ipynb',
 '05_market_basket_analysis.ipynb',
 '06_clv_analysis.ipynb',
 '07_supply_chain_analysis.ipynb',
 '08_executive_recommendations.ipynb']

In [8]:
import os

os.listdir("../data")

['blinkit_customers.csv',
 'blinkit_customer_feedback.csv',
 'blinkit_delivery_performance.csv',
 'blinkit_inventory.csv',
 'blinkit_inventoryNew.csv',
 'blinkit_marketing_performance.csv',
 'blinkit_orders.csv',
 'blinkit_order_items.csv',
 'blinkit_products.csv',
 'Category_Icons.xlsx',
 'Rating_Icon.xlsx']

In [9]:
import pandas as pd
import numpy as np

customers = pd.read_csv("../data/blinkit_customers.csv")

orders = pd.read_csv("../data/blinkit_orders.csv")

order_items = pd.read_csv("../data/blinkit_order_items.csv")

products = pd.read_csv("../data/blinkit_products.csv")

inventory = pd.read_csv("../data/blinkit_inventory.csv")

inventory_new = pd.read_csv("../data/blinkit_inventoryNew.csv")

delivery = pd.read_csv("../data/blinkit_delivery_performance.csv")

feedback = pd.read_csv("../data/blinkit_customer_feedback.csv")

marketing = pd.read_csv("../data/blinkit_marketing_performance.csv")

In [10]:
output_path = "../exports/cleaned_data/"

In [11]:
customers.to_csv(f"{output_path}customers_clean.csv", index=False)

orders.to_csv(f"{output_path}orders_clean.csv", index=False)

order_items.to_csv(f"{output_path}order_items_clean.csv", index=False)

products.to_csv(f"{output_path}products_clean.csv", index=False)

inventory.to_csv(f"{output_path}inventory_clean.csv", index=False)

inventory_new.to_csv(f"{output_path}inventory_new_clean.csv", index=False)

delivery.to_csv(f"{output_path}delivery_clean.csv", index=False)

feedback.to_csv(f"{output_path}feedback_clean.csv", index=False)

marketing.to_csv(f"{output_path}marketing_clean.csv", index=False)

In [12]:
import os

os.listdir("../exports/cleaned_data")

['customers_clean.csv',
 'delivery_clean.csv',
 'feedback_clean.csv',
 'inventory_clean.csv',
 'inventory_new_clean.csv',
 'marketing_clean.csv',
 'orders_clean.csv',
 'order_items_clean.csv',
 'products_clean.csv']